default: &default
  adapter: postgresql
  #host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  encoding: unicode
  username: postgres
  password: postgres

development:
  <<: *default
  host: localhost
  database: my_app_name_development

test:
  <<: *default
  host: localhost
  database: my_app_name_test

production:
  <<: *default
  database: my_app_name
  pool:     16
  username:
  password:
