default: &default
  adapter: postgresql
  #host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 16 } %>
  encoding: unicode
  username: postgres
  password: postgres

development:
  <<: *default
  host: localhost
  database: rails_starter_app_development

test:
  <<: *default
  host: localhost
  database: rails_starter_app_test

production:
  <<: *default
  database: rails_starter_app
  username:
  password:
